### ISSUE TITLE
Could not find function

### ISSUE THREAD

**Issue by seaurching** [valsaven/md5hash#1]
/usr/local/bin/python3.7 /Users/miyamoto/Documents/filencrypt/sss.py
Traceback (most recent call last):
  File "/Users/miyamoto/Documents/filencrypt/sss.py", line 105, in <module>
    from md5hash import scan
ImportError: cannot import name 'scan' from 'md5hash' (/usr/local/lib/python3.7/site-packages/md5hash/__init__.py)

**Comment by valsaven** [comment]
Thank you!
I haven't checked this library for five years, but I think it works now.

**Comment by seaurching** [comment]
@valsaven There is not function for new python version
